### ISSUE TITLE
Uncaught Error: Assertion Failed: A string cannot be pushed into the buffer after a fragment

### ISSUE THREAD

**Issue by srisonti** [luxbet/ember-cli-llama-table#12]
I'm having some trouble getting your component to work in my Ember application. I copied your test data to make sure it's working by itself, first, and I'm getting an error in the console: `Uncaught Error: Assertion Failed: A string cannot be pushed into the buffer after a fragment`. This error only occurs when I include the `llama-table` Handlebars snippet in the template - as soon as I remove it, the page and everything load correctly.

Here's a couple of screenshots of my console:
![image](https://cloud.githubusercontent.com/assets/869246/6570086/8412d970-c6c2-11e4-9e10-13ce29df2421.png)
![image](https://cloud.githubusercontent.com/assets/869246/6570089/9924532a-c6c2-11e4-928f-cfe0bacd0ed5.png)

I'm not entirely sure what the issue since the error has me digging through Ember for the most part. However, I noticed in your `bower.json` file that you're using `ember 1.9.1`. I found [this issue](https://github.com/emberjs/ember.js/issues/10400) which only people upgrading from 1.9 to 1.10 are having. Any thoughts on a fix for this? I dug through your addon a bit, but unfortunately I'm still somewhat of a beginner when it comes to Ember.

In case it helps, here are my files:

`OrdersController`:

        import Ember from 'ember';
        import config from '../config/environment';
        import DynamicTableMixin from '../mixins/dynamic-table';

        export default Ember.Controller.extend(DynamicTableMixin, {
          ordersTable: function() {
            return this.get('dynamicTable').create({
              endpoint: config.webUrl + 'user/orders/list/',
              page: 1,
              limit: 25
            })
          },
          createRow: function(order) {
            return order;
          },
          tableColumns: [
            {
              name: 'foo',
              label: 'Foo',
              order: 1
            },
            {
              name: 'bar',
              label: 'Bar',
              order: 2
            }
          ],
          tableData: [
            {
              foo: 'abc',
              bar: 'def'
            },
            {
              foo: 'ghi',
              bar: 'jkl'
            }
          ],
          tableConfig: {
            sortProperties: ['foo', 'bar']
          }
        });

`OrdersRoute`:

        import Ember from 'ember';

        export default Ember.Route.extend({
          renderTemplate: function() {
            this.render('orders.headline', {
              outlet: 'headline'
            });
            this.render('orders.cta', {
              outlet: 'cta'
            });
            this.render('orders', {
              outlet: 'main',
              controller: 'orders'
            });
          }
        });

`Orders` template:

        {{llama-table rows=tableData columns=tableColumns config=tableConfig}}

Let me know if there's anything else I can provide to help!

Cheers

**Comment by j-** [comment]
Hi Sri. Thanks for the detailed report! I will investigate when I get a chance. In the mean time, can you try installing version 0.3.3 (d32975f769bb33b82175e29761809daa0ff86d9f) of llama table and let me know if that makes a difference? The upgrade to Ember 1.9.1 was introduced in version 0.3.4 (the latest release) and has caused several issues so far.

**Comment by tolgaek** [comment]
+1 Having the same issue

**Comment by tolgaek** [comment]
I can confirm that using 0.3.3. fixed the issue

**Comment by j-** [comment]
Hi Tolga. I've just released v0.3.7 (87703aedd61930f5129939ba023d73d40c042dee). It reverts Ember to version 1.8.1 which was in use in Llama Table before the upgrade. Can you please confirm that this release fixes the issue?

**Comment by szachara** [comment]
Same problem here, Ember 1.11.0, Ember CLI 0.2.2, ember-cli-llama-table 0.3.8

**Comment by j-** [comment]
Hey guys I recreated and fixed the issue for version 0.3.9 (d726ea5a18f6e2ada1386ff44ab23faca86fa913). Please let me know if there are any more issues.

**Comment by tolgaek** [comment]
Thanks @j- . Just updated to 0.3.9, seems to be working fine

**Comment by szachara** [comment]
It works now, thank you.
