### ISSUE TITLE
How to increase the Cell / Row Height

### ISSUE THREAD

**Issue by reflections55** [luxbet/ember-cli-llama-table#23]
How to increase the row or cell height. I tried setting using css but since the height is set in element style couldn't know how to overide. Can you please help me in increasing the cell height size.

div id="ember2058" class="ember-view llama-cell llama-body-cell" tabindex="0" style="**margin-bottom: 0px; height: 30px;**">

**element.style {
  margin-bottom: 0px;
  height: 30px;
}**

**Comment by j-** [comment]
Hey mate. At the moment Llama Table respects the `height` property on each row to determine the row height, with a fixed default of 30 pixels.

I've added a simple demo which generates row data with random heights: http://luxbet.github.io/ember-cli-llama-table/#/row-heights

Here's the code that goes with it: https://github.com/j-/ember-cli-llama-table/blob/478aec7eeadffca1be94606b00b98afafd3cb9e2/tests/dummy/app/controllers/row-heights.js#L35-L39
