### ISSUE TITLE
How to Specify the width of the particular column?

### ISSUE THREAD

**Issue by reflections55** [luxbet/ember-cli-llama-table#9]
I am not sure how to specify the width size for a particular column. Currently I see all columns have same size. Suppose if I know that a particular column content length will be of 2 or 3 characters for eg. age column, then I should be able to set the column width as 30px. Is this option is currently supported?. If not is there any work around to achieve it. I think this feature more important for any product. Thanks.

**Comment by j-** [comment]
Column definitions can specify a `width` property as well as a `minWidth` and a `maxWidth` -- all of which are at the moment undocumented. I will document these properties.

**Comment by j-** [comment]
To clarify, these properties are numeric values as a number of pixels.

**Comment by reflections55** [comment]
That is Great News. Will try now and close the Issue.
